### PR TITLE
[RFT] use ath10k-ct on unstable qca9886 radios

### PR DESCRIPTION
**Pull request by spolack**
I'm running out of ideas, lets try candela tech driver on the affected devices.

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Please fix the linting. :)

**Review by PolynomialDivision — APPROVED** [review]

**Comment by spolack** [comment]
wow that was quick

**Comment by PolynomialDivision** [comment]
Can we merge? This is fixing for me the issues.

**Review by Noki — APPROVED** [review]
Tested on stable EAP225 outdoor v1, so I think we are good to merge this.

**Pull request merged**
