### PR TITLE
strom: added bbbvpn VLAN

### PR DESCRIPTION
**Pull request by Noki**

### CODE REVIEW

**Comment by pmelange** [comment]
Is there a way to have it only generate an OLSRd config and no babel config?  Maybe give it only an ipv4 address.

**Comment by pmelange** [comment]
*for VLAN 1312

**Comment by pmelange** [comment]
when an interface doesn't have an ip6 address, should it maybe then look like this?
```
config interface
	option 'ifname' 'mesh_XXXXX'
	option 'ignore' 'true'
```

**Comment by pmelange** [comment]
Interfaces mesh_perl and mesh_tu should probably be ```Mode 'mesh'```

**Comment by pmelange** [comment]
Can we also get snmp statistics?

**Comment by Noki** [comment]
> when an interface doesn't have an ip6 address, should it maybe then look like this?
> 
> ```
> config interface
> 	option 'ifname' 'mesh_XXXXX'
> 	option 'ignore' 'true'
> ```

I would keep it as is for now. If you want you can start a discussion about this in the bbb-configs channel. I don't really have an option about this.

**Pull request merged**
