### PR TITLE
model: wdr4900: bump wdr4900 to 22.03

### PR DESCRIPTION
**Pull request by PolynomialDivision**
WDR4900 boots now with extra spi-loader.

### CODE REVIEW

**Comment by Akira25** [comment]
Did they merge it in OpenWrt already?

**Comment by PolynomialDivision** [comment]
Yes. Already to 22.03
- https://github.com/openwrt/openwrt/commit/f7a43e46065609910bdd2fa6f97ffa1deeda222b
- https://github.com/openwrt/openwrt/commit/5db6914f7cfddd1c3cb8a46017d4360e1ec26c5d

**Review by Akira25 — APPROVED** [review]
Looks good to me.

**Comment by PolynomialDivision** [comment]
There is a issue with the mbedtls library. We have to wait until this is fixed. However, snapshot works. ^^

**Comment by spolack** [comment]
Any update?

**Comment by PolynomialDivision** [comment]
Looks like a gcc bug:
https://github.com/openwrt/openwrt/pull/11003

We could go snapshot.

**Comment by spolack** [comment]
You upstream issue is resolved. Would you test again?

**Comment by PolynomialDivision** [comment]
I think I finally found it:
https://github.com/openwrt/openwrt/pull/11624

**Comment by PolynomialDivision** [comment]
Yes. It is fixing everything. I will merge.

**Pull request merged**
