### PR TITLE
corerouter: instead of domains use hostrecords

### PR DESCRIPTION
**Pull request by PolynomialDivision**
We actually talk about hosts and not domains. So lets switch to hostrecords.

### CODE REVIEW

**Comment by pktpls** [comment]
What is the difference?

**Comment by Noki** [comment]
> What is the difference?

Between a domain and a host? The domain includes the domain and all subdomains within, the host is only a single host. So a domain example.com usually includes "example.com", and "*.example.com", but the host is only that specific host.

**Comment by Noki** [comment]
Maybe it would also be a good idea to use subdomains for the different devices in a core-router setup like:

example-core.olsr - corerouter
ap1.example-core.olsr - accesspoint

When registering IPs the name is considered uniqu, so example-core will be kind of protected, but all the other hosts aren't registered and could therefore exist twice in the network.

**Comment by pktpls** [comment]
I'm open for anything but I still don't understand the change in this PR :-)

Is it that we currently define entire zones in dnsmasq, while we actually only need individual host entries similar to what's in /etc/hosts?

**Pull request closed without merging**
