### PR TITLE
ssh-key added and new Channel Assignment

### PR DESCRIPTION
**Pull request by FFHener**
I added a ssh-key and Changed the channel of AP4 to a non DFS-channel because of #17

### CODE REVIEW

**Comment by spolack** [comment]
I noticed there are only two channels available for 40MHz Bandwith in non-dfs range:

40 (is choosen fallback if using 36 with 40MHz bw)
48 (is choosen if using Channel 44 with 40MHZ bw)

I'd propose to assign them in a A B A B scheme, depending on the distance of the APs

**Comment by FFHener** [comment]
Do i have to use Option 1 or 2 in the networks-file?
1)
A: 36-40
B: 44-40
2)
A: 40-40
B: 48-40

**Comment by spolack** [comment]
Both should be fine.

**Comment by FFHener** [comment]
Channels now shoud be good and ready to merge

**Pull request merged**
