### PR TITLE
enforce http to https redirect as within standard falter

### PR DESCRIPTION
**Pull request by Noki**
make secure access to the web interface the default as in standard falter

### CODE REVIEW

**Comment by Noki** [comment]
please let me know if there is a more elegant way to just set `option redirect_https '1'` without creating a full config file duplicating the openwrt defaults.

**Comment by PolynomialDivision** [comment]
You forgot to symlink corerouter. ;)

**Comment by Noki** [comment]
no, the symlink is in there as well. look again. ;-)

**Comment by Akira25** [comment]
@Noki Did you test this on a node? I'm not sure, if LuCI gets installed on current bbb-configs.

**Comment by Noki** [comment]
@Akira25 Sure thing! You can test it here: http://e16-core.olsr/

**Comment by Akira25** [comment]
Looks good to me.

**Pull request merged**
