### PR TITLE
dawn: add dawn

### PR DESCRIPTION
**Pull request by PolynomialDivision**

### CODE REVIEW

**Comment by Akira25** [comment]
could you please provide a short description what dawn is about and add some note on it to the readme please?

**Comment by PolynomialDivision** [comment]
I'm still unsure how to correclty add this due to the configs that differ between 21.02 and master. I think i have to soemhow go to new dawn version also in 21.02.

**Comment by Akira25** [comment]
Can we close this? There was no advancement for a long time and this PR has merge-conflicts.

**Comment by spolack** [comment]
@Akira25 hasnt received an answer. Closing

**Pull request closed without merging**
