### PR TITLE
Maintenance huette & huette15

### PR DESCRIPTION
**Pull request by pktpls**
- add @pktpls ssh key
- codify our wifi settings
- remove mentions of huette15-vm

### CODE REVIEW

**Comment by Akira25** [comment]
@pktpls the CI failed on huette-vm. Does this happen on your machine too?

**Comment by pktpls** [comment]
huette-vm is supposed to be removed with the last commit

**Comment by PolynomialDivision** [comment]
> @pktpls the CI failed on huette-vm. Does this happen on your machine too?

That is a failure of the CI. Can not handle removing of hosts. :S

**Comment by Akira25** [comment]
If the CI fails regularily on correct PRs, we don't need it, in my opinion. Its just a useless waste of computing power then. :(

**Pull request merged**
