### PR TITLE
teufelsberg: add rocket-sectors

### PR DESCRIPTION
**Pull request by Koltonowski**

### CODE REVIEW

**Comment by Noki** [comment]
please fix the linter issues!

**Comment by pktpls** [comment]
It's fine, my editor will remove that one trailing space character next time.

We really need to discuss those style linters. They don't fix a single concrete problem. I am even in favor of consistent coding style, but they way we do it right now is counterproductive and very frustrating.

**Comment by pktpls** [comment]
(Shellcheck is useful, and other tools that actually check the semantic meaning of code)

**Comment by Noki** [comment]
I just corrected it. Of course we can discuss linter rules and disable some, however in yaml identation has a meaning and should therefore be checked.

**Pull request merged**
