### PR TITLE
tunnelmanager: change default metric for client uplinks

### LINKED ISSUE #308: OLSRd wireguard connections cause bbb-traffic to go through (slow/low latency) DSL connections
The current implementation via wireguard tunnels connecting to multiple gw nodes causes bbb traffic to go through the private DSL connection (which can be slow and have a poor latency).

```
~$ mtr a.bbb-vpn.olsr --report
Start: 2022-08-16T11:58:20+0200
HOST: automaton                   Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- frei.funk                  0.0%    10    0.4   0.4   0.3   0.4   0.0
  2.|-- mid9.bht-core.olsr         0.0%    10   13.3   7.4   5.1  13.3   2.6
  3.|-- mid12.segen-core.olsr      0.0%    10   17.2  12.8  10.6  17.2   2.0
  4.|-- mid8.saarbruecker-gw.olsr  0.0%    10    9.5  12.7   9.5  17.4   2.5
  5.|-- newyorck-core.olsr         0.0%    10   51.7  53.3  43.0  76.9   9.3
  6.|-- mid3.ak36-gw.olsr          0.0%    10   87.2 112.6  66.5 256.1  52.9
  7.|-- a.bbb-vpn.olsr             0.0%    10   79.7 115.0  72.3 223.8  50.0
```

The best scenario is for the packets __not__ to go through a private tunnel-based connection twice (in this example once into newyorck and once out from newyorck) in order to reach another part the backbone.  The implementation on the falter firmware, which creates a tunneldigger interface to the bbb-vpn server prevents this kind of short-cut.  

In my opinion, the setup for bbb-configs is a very poor network model which need to be implemented differently and which I consider a bug.  I recommend that the bbb-configs team consider changing their OLSRd island connections to use the same implementation style as the falter firmware using tunneldigger.

@Noki @booo @robertfoss @spolack @rtznprmpftl @freifunkoperator @PolynomialDivision

### PR DESCRIPTION
**Pull request by Noki**
This should fix #308 and once merged #334 will add this to the documentation.

### CODE REVIEW

**Comment by Noki** [comment]
5120 might not be enough for babel >1,7 MBit/s - with 25600 the traffic seems to be limited on the uplink interfaces <200KBit/s

**Comment by spolack** [comment]
That should not make a difference in terms of throughput?

**Comment by spolack** [comment]
Looking good to me. If you have tested this change and its working, feel free to merge.

**Comment by Noki** [comment]
I changed the metrics to 0.4 as LQM for OLSR and 12800 as metric for babel. With 0.5 I still had OLSR routes via the wireguard tunnels (`ssh root@10.31.174.1 "echo /routes | nc 127.0.0.1 9090" | jq '.routes[] | select( .networkInterface | startswith("wg_"))'` with 0.4 all routes are via the wlan interfaces, which is what we want for an backup uplink. 0.4 results in 12.5 hops and therefore I went with 12.5*1024=12800 as a metric for babel. 1024 was chosen as a multiplier, as we often use 1024 for 2GHz links.

**Pull request merged**
