### PR TITLE
model: add GL.iNet Beryl AX (GL-MT3000)

### PR DESCRIPTION
**Pull request by Noki**

### CODE REVIEW

**Comment by Noki** [comment]
Fine for me. I just wanted to finally finish and merge https://github.com/freifunk-berlin/bbb-configs/pull/933

**Comment by Noki** [comment]
@armari4n did you have the time to test the Beryl AX?

**Comment by ZuquetuPlexis** [comment]
@armari4n und ich starten heute den Test

**Comment by Noki** [comment]
Test was reported to be successful at hacrafu-gobbetti-core.

**Pull request merged**
