### PR TITLE
gateway: allow inbound for cryptpad.berlin service

### PR DESCRIPTION
**Pull request by pktpls**
I'm setting up a Cryptpad instance :lock:

### CODE REVIEW

**Comment by Noki** [comment]
I think we should start adding information about which core-router handles the prefix and also state this as mandatory.

**Comment by pktpls** [comment]
> which core-router handles the prefix

The cryptpad host won't be in bbb-configs

**Review by Noki — APPROVED** [review]
looks good to me

**Comment by pktpls** [comment]
Hm, this should have built the configs for all gateway hosts, but didn't. I'll fix that separately.

**Pull request merged**
