### PR TITLE
APK

### PR DESCRIPTION
**Pull request by pktpls**
Related: https://github.com/openwrt/routing/pull/1085 & https://github.com/freifunk-berlin/ansible/pull/139

### CODE REVIEW

**Comment by spolack** [comment]
I think commit [version: fix snapshot imagebuilder url](https://github.com/freifunk-berlin/bbb-configs/pull/1073/commits/70e0a26367dc2fdc80acbbe7a42c1a7ace429050) can be dropped. That should be covered by https://github.com/freifunk-berlin/bbb-configs/commit/08873f6fbb368192b8f85ec98e74aecb238266c5 which was merged last week by yourself.

**Comment by pktpls** [comment]
> I think commit [version: fix snapshot imagebuilder url](https://github.com/freifunk-berlin/bbb-configs/pull/1073/commits/70e0a26367dc2fdc80acbbe7a42c1a7ace429050) can be dropped. That should be covered by https://github.com/freifunk-berlin/bbb-configs/commit/08873f6fbb368192b8f85ec98e74aecb238266c5 which was merged last week by yourself.

No, you didn't test that and broke it :beers:

**Comment by spolack** [comment]
Ups i tested that with a device i was strongly assuming to run on snapshot. Let me fix that..

**Comment by spolack** [comment]
I'm confused.. actually i wasnt inteding to fix snapshot, but to fix 24.10. 

Can you rebase on that branch commits which contain the fix and a small change to the inline var templating on the feed_url, which now follows ansible common practice..
https://github.com/freifunk-berlin/bbb-configs/commits/fewfixes/

**Comment by pktpls** [comment]
> Can you rebase on that branch commits which contain the fix and a small change to the inline var templating on the feed_url, which now follows ansible common practice..
https://github.com/freifunk-berlin/bbb-configs/commits/fewfixes/

I picked the templating commit, didn't know the inline templates are evaluated lazily, very useful!

The URL string construction is perhaps a little overengineered for my taste - a) we have the version group_var exactly for this, b) we need a snapshot-specific feed URL as well, and c) I don't want to spend mental capacity only to figure out a simple URL string. And finally there's only 2 (at most 3) possible values for that URL string anyway :beers: :)

**Comment by pktpls** [comment]
The falter feed is now also set up within the image

```
root@pktpls-core:~# apk update
fetch https://downloads.openwrt.org/snapshots/targets/x86/64/packages/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/x86_64/base/packages.adb
fetch https://downloads.openwrt.org/snapshots/targets/x86/64/kmods/6.6.61-1-fcc34a80749f2bb1217ba31a0b7e4e32/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/x86_64/luci/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/x86_64/packages/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/x86_64/routing/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/x86_64/telephony/packages.adb
fetch https://firmware.berlin.freifunk.net/feed/testbuildbot/packages/x86_64/falter/packages.adb
OK: 10510 distinct packages available

```

**Comment by pktpls** [comment]
Ping - bbb-configs mit snapshot ist jetzt schon einen Monat kaputt

**Comment by spolack** [comment]
Unfortune, as you did not develop in a freifunk-berlin/bbb-configs branch i cant test easily... Lets merge and test later...

**Pull request merged**
