### PR TITLE
locations: add remaining missing contacts

### PR DESCRIPTION
**Pull request by pktpls**
- agym: community, stammt aus der MABB-Förderung, damals wurde das als Projekt zusammen mit einer AG an der Schule aufgebaut
- ak36: community, Zugang über den Speedbone-Kontakt oder die Amateurfunker
- habersaath: stadtfunk
- ohlauer: community, Zugang über up42 GmbH bzw. Hausmeister
- saarbruecker: community, Zugang über Hausmeister

---

- dragonkiez_buero: cc @pmelange you seem to be working with them
- grueni: cc @robertfoss this location can probably be removed?
- manstein10: wird von @ideesnoires gepflegt
- newyorck: wird von @noxilixon gepflegt, willst du eine

### CODE REVIEW

**Review by Akira25 — APPROVED** [review]
Looks good to me. Thank you very much for your effort!

**Comment by Akira25** [comment]
The Pipeline-Error is something that happend while using the image-builder. So I don't think its anyhow related to the changes. Therefore merging.

**Comment by pmelange** [comment]
> * dragonkiez_buero: cc @pmelange you seem to be working with them

pr #383 has the added contact.  It's waiting to be merged.  But I am not sure about one of the commits, specifically "model unifiac-mesh: reduce image size".  If there is a better way to do this, please comment in the pr.  Otherwise, I would appreciate it if someone were to merge that pr.

**Comment by robertfoss** [comment]
About grueni, it's not a location I've had anything to do with. And as far as I know, it is not the same as gruni73.

**Pull request merged**
